namespace Hysj.Client.Resources.Localization;

public static class Strings
{
    public static Dictionary<string, string> GetStrings(string lang) => lang switch
    {
        "no" => Norwegian,
        "es" => Spanish,
        "fr" => French,
        "de" => German,
        "ar" => Arabic,
        "zh" => Chinese,
        "pt" => Portuguese,
        "ru" => Russian,
        "ja" => Japanese,
        _    => English,
    };

    // ── ENGLISH (default) ──────────────────────────────────────────────
    private static readonly Dictionary<string, string> English = new()
    {
        // General
        ["app_name"]            = "hysj",
        ["cancel"]              = "Cancel",
        ["save"]                = "Save",
        ["delete"]              = "Delete",
        ["confirm"]             = "Confirm",
        ["loading"]             = "Loading...",
        ["error"]               = "Error",
        ["ok"]                  = "OK",
        ["back"]                = "Back",
        ["send"]                = "Send",
        ["search"]              = "Search",
        ["settings"]            = "Settings",
        ["language"]            = "Language",
        ["select_language"]     = "Select language",

        // Auth
        ["login"]               = "Log in",
        ["register"]            = "Register",
        ["username"]            = "Username",
        ["password"]            = "Password",
        ["login_title"]         = "Welcome back",
        ["login_subtitle"]      = "Sign in to continue",
        ["register_title"]      = "Create account",
        ["totp_title"]          = "Two-factor auth",
        ["totp_code"]           = "Enter 6-digit code",
        ["totp_hint"]           = "Open your authenticator app",
        ["logout"]              = "Log out",

        // Conversations
        ["conversations"]       = "Conversations",
        ["welcome"]             = "Welcome, {0}",
        ["new_conversation"]    = "New conversation",
        ["deleted_conversation"]= "Conversation deleted",
        ["all"]                 = "All",
        ["groups"]              = "Groups",
        ["encrypted"]           = "Encrypted",

        // Chat
        ["type_message"]        = "Message",
        ["active_now"]          = "Active now",
        ["encrypted_label"]     = "encrypted",
        ["message_delivered"]   = "Delivered",
        ["message_read"]        = "Read",
        ["anonymous_badge"]     = "You are anonymous in this group as «{0}»",
        ["today"]               = "Today",
        ["yesterday"]           = "Yesterday",

        // Groups
        ["create_group"]        = "Create group",
        ["group_name"]          = "Group name",
        ["group_type"]          = "Group type",
        ["normal_group"]        = "Normal",
        ["anonymous_group"]     = "Anonymous",
        ["anonymous_desc"]      = "Members see aliases only",
        ["normal_desc"]         = "Members see real names",
        ["cannot_change"]       = "Cannot be changed after creation",
        ["members_can_add"]     = "Members can invite",
        ["add_member"]          = "Add member",
        ["remove_member"]       = "Remove member",
        ["transfer_admin"]      = "Transfer admin",
        ["leave_group"]         = "Leave group",
        ["group_members"]       = "Members",

        // Security
        ["security"]            = "Security",
        ["encryption_status"]   = "Encryption status",
        ["double_ratchet"]      = "Double Ratchet",
        ["ratchet_desc"]        = "Forward secrecy per message",
        ["post_quantum"]        = "Post-Quantum",
        ["quantum_desc"]        = "ECC + Kyber hybrid",
        ["sealed_sender"]       = "Sealed Sender",
        ["sealed_desc"]         = "Sender hidden from server",
        ["onion_routing"]       = "Onion Routing",
        ["onion_desc"]          = "IP hidden via 3 relay nodes",
        ["my_devices"]          = "My devices",
        ["this_device"]         = "This device",
        ["danger_zone"]         = "DANGER ZONE",
        ["wipe_conversation"]   = "Wipe conversation",
        ["wipe_device"]         = "Wipe device",
        ["wipe_all"]            = "Wipe everything",
        ["wipe_all_desc"]       = "Emergency — requires 2FA",
        ["two_factor"]          = "Two-factor auth",
        ["auto_delete"]         = "Auto-delete",
        ["relay_nodes"]         = "ONION ROUTING",

        // Contacts
        ["contacts"]            = "Contacts",
        ["add_contact"]         = "Add contact",

        // Settings
        ["account"]             = "Account",
        ["appearance"]          = "Appearance",
        ["notifications"]       = "Notifications",
        ["about"]               = "About",
        ["version"]             = "Version",
    };

    // ── NORWEGIAN ─────────────────────────────────────────────────────
    private static readonly Dictionary<string, string> Norwegian = new()
    {
        ["app_name"]            = "hysj",
        ["cancel"]              = "Avbryt",
        ["save"]                = "Lagre",
        ["delete"]              = "Slett",
        ["confirm"]             = "Bekreft",
        ["loading"]             = "Laster...",
        ["error"]               = "Feil",
        ["ok"]                  = "OK",
        ["back"]                = "Tilbake",
        ["send"]                = "Send",
        ["search"]              = "Søk",
        ["settings"]            = "Innstillinger",
        ["language"]            = "Språk",
        ["select_language"]     = "Velg språk",
        ["login"]               = "Logg inn",
        ["register"]            = "Registrer",
        ["username"]            = "Brukernavn",
        ["password"]            = "Passord",
        ["login_title"]         = "Velkommen tilbake",
        ["login_subtitle"]      = "Logg inn for å fortsette",
        ["register_title"]      = "Opprett konto",
        ["totp_title"]          = "To-faktor autentisering",
        ["totp_code"]           = "Skriv inn 6-sifret kode",
        ["totp_hint"]           = "Åpne autentiseringsappen din",
        ["logout"]              = "Logg ut",
        ["conversations"]       = "Samtaler",
        ["welcome"]             = "Velkommen, {0}",
        ["new_conversation"]    = "Ny samtale",
        ["deleted_conversation"]= "Samtale slettet",
        ["all"]                 = "Alle",
        ["groups"]              = "Grupper",
        ["encrypted"]           = "Kryptert",
        ["type_message"]        = "Melding",
        ["active_now"]          = "Aktiv nå",
        ["encrypted_label"]     = "kryptert",
        ["message_delivered"]   = "Levert",
        ["message_read"]        = "Lest",
        ["anonymous_badge"]     = "Du er anonym i denne gruppen som «{0}»",
        ["today"]               = "I dag",
        ["yesterday"]           = "I går",
        ["create_group"]        = "Opprett gruppe",
        ["group_name"]          = "Gruppenavn",
        ["group_type"]          = "Gruppetype",
        ["normal_group"]        = "Normal",
        ["anonymous_group"]     = "Anonym",
        ["anonymous_desc"]      = "Medlemmer ser kun alias",
        ["normal_desc"]         = "Medlemmer ser ekte navn",
        ["cannot_change"]       = "Kan ikke endres etter opprettelse",
        ["members_can_add"]     = "Medlemmer kan invitere",
        ["add_member"]          = "Legg til medlem",
        ["remove_member"]       = "Fjern medlem",
        ["transfer_admin"]      = "Overfør admin",
        ["leave_group"]         = "Forlat gruppe",
        ["group_members"]       = "Medlemmer",
        ["security"]            = "Sikkerhet",
        ["encryption_status"]   = "Krypteringsstatus",
        ["double_ratchet"]      = "Double Ratchet",
        ["ratchet_desc"]        = "Forward secrecy per melding",
        ["post_quantum"]        = "Post-Quantum",
        ["quantum_desc"]        = "ECC + Kyber hybrid",
        ["sealed_sender"]       = "Sealed Sender",
        ["sealed_desc"]         = "Avsender skjult for server",
        ["onion_routing"]       = "Onion Routing",
        ["onion_desc"]          = "IP skjult via 3 relay-noder",
        ["my_devices"]          = "Mine enheter",
        ["this_device"]         = "Denne enheten",
        ["danger_zone"]         = "FARESONE",
        ["wipe_conversation"]   = "Slett samtale",
        ["wipe_device"]         = "Wipe enhet",
        ["wipe_all"]            = "Slett ALT",
        ["wipe_all_desc"]       = "Nødknapp — krever 2FA",
        ["two_factor"]          = "To-faktor autentisering",
        ["auto_delete"]         = "Auto-slett",
        ["relay_nodes"]         = "ONION ROUTING",
        ["contacts"]            = "Kontakter",
        ["add_contact"]         = "Legg til kontakt",
        ["account"]             = "Konto",
        ["appearance"]          = "Utseende",
        ["notifications"]       = "Varsler",
        ["about"]               = "Om",
        ["version"]             = "Versjon",
    };

    // ── SPANISH ───────────────────────────────────────────────────────
    private static readonly Dictionary<string, string> Spanish = new()
    {
        ["app_name"]            = "hysj",
        ["cancel"]              = "Cancelar",
        ["save"]                = "Guardar",
        ["delete"]              = "Eliminar",
        ["confirm"]             = "Confirmar",
        ["loading"]             = "Cargando...",
        ["error"]               = "Error",
        ["ok"]                  = "OK",
        ["back"]                = "Volver",
        ["send"]                = "Enviar",
        ["search"]              = "Buscar",
        ["settings"]            = "Configuración",
        ["language"]            = "Idioma",
        ["select_language"]     = "Seleccionar idioma",
        ["login"]               = "Iniciar sesión",
        ["register"]            = "Registrarse",
        ["username"]            = "Usuario",
        ["password"]            = "Contraseña",
        ["login_title"]         = "Bienvenido",
        ["login_subtitle"]      = "Inicia sesión para continuar",
        ["register_title"]      = "Crear cuenta",
        ["totp_title"]          = "Autenticación en dos pasos",
        ["totp_code"]           = "Ingresa el código de 6 dígitos",
        ["totp_hint"]           = "Abre tu app de autenticación",
        ["logout"]              = "Cerrar sesión",
        ["conversations"]       = "Conversaciones",
        ["welcome"]             = "Bienvenido, {0}",
        ["new_conversation"]    = "Nueva conversación",
        ["deleted_conversation"]= "Conversación eliminada",
        ["all"]                 = "Todas",
        ["groups"]              = "Grupos",
        ["encrypted"]           = "Cifrado",
        ["type_message"]        = "Mensaje",
        ["active_now"]          = "Activo ahora",
        ["encrypted_label"]     = "cifrado",
        ["message_delivered"]   = "Entregado",
        ["message_read"]        = "Leído",
        ["anonymous_badge"]     = "Eres anónimo en este grupo como «{0}»",
        ["today"]               = "Hoy",
        ["yesterday"]           = "Ayer",
        ["create_group"]        = "Crear grupo",
        ["group_name"]          = "Nombre del grupo",
        ["group_type"]          = "Tipo de grupo",
        ["normal_group"]        = "Normal",
        ["anonymous_group"]     = "Anónimo",
        ["anonymous_desc"]      = "Los miembros ven alias",
        ["normal_desc"]         = "Los miembros ven nombres reales",
        ["cannot_change"]       = "No se puede cambiar después de crear",
        ["members_can_add"]     = "Miembros pueden invitar",
        ["security"]            = "Seguridad",
        ["encryption_status"]   = "Estado de cifrado",
        ["double_ratchet"]      = "Double Ratchet",
        ["ratchet_desc"]        = "Secreto perfecto por mensaje",
        ["post_quantum"]        = "Post-Cuántico",
        ["quantum_desc"]        = "Híbrido ECC + Kyber",
        ["sealed_sender"]       = "Remitente sellado",
        ["sealed_desc"]         = "Remitente oculto al servidor",
        ["onion_routing"]       = "Enrutamiento Cebolla",
        ["onion_desc"]          = "IP oculta vía 3 nodos relay",
        ["danger_zone"]         = "ZONA DE PELIGRO",
        ["contacts"]            = "Contactos",
        ["add_contact"]         = "Añadir contacto",
        ["account"]             = "Cuenta",
    };

    // ── FRENCH ────────────────────────────────────────────────────────
    private static readonly Dictionary<string, string> French = new()
    {
        ["app_name"]            = "hysj",
        ["cancel"]              = "Annuler",
        ["save"]                = "Enregistrer",
        ["delete"]              = "Supprimer",
        ["confirm"]             = "Confirmer",
        ["loading"]             = "Chargement...",
        ["error"]               = "Erreur",
        ["ok"]                  = "OK",
        ["back"]                = "Retour",
        ["send"]                = "Envoyer",
        ["search"]              = "Rechercher",
        ["settings"]            = "Paramètres",
        ["language"]            = "Langue",
        ["select_language"]     = "Choisir la langue",
        ["login"]               = "Se connecter",
        ["register"]            = "S'inscrire",
        ["username"]            = "Nom d'utilisateur",
        ["password"]            = "Mot de passe",
        ["login_title"]         = "Bon retour",
        ["login_subtitle"]      = "Connectez-vous pour continuer",
        ["register_title"]      = "Créer un compte",
        ["totp_title"]          = "Authentification deux facteurs",
        ["totp_code"]           = "Entrez le code à 6 chiffres",
        ["totp_hint"]           = "Ouvrez votre app d'authentification",
        ["logout"]              = "Se déconnecter",
        ["conversations"]       = "Conversations",
        ["welcome"]             = "Bienvenue, {0}",
        ["new_conversation"]    = "Nouvelle conversation",
        ["deleted_conversation"]= "Conversation supprimée",
        ["all"]                 = "Toutes",
        ["groups"]              = "Groupes",
        ["encrypted"]           = "Chiffré",
        ["type_message"]        = "Message",
        ["active_now"]          = "Actif maintenant",
        ["encrypted_label"]     = "chiffré",
        ["anonymous_badge"]     = "Vous êtes anonyme dans ce groupe en tant que «{0}»",
        ["create_group"]        = "Créer un groupe",
        ["group_name"]          = "Nom du groupe",
        ["anonymous_group"]     = "Anonyme",
        ["normal_group"]        = "Normal",
        ["security"]            = "Sécurité",
        ["double_ratchet"]      = "Double Ratchet",
        ["sealed_sender"]       = "Expéditeur scellé",
        ["onion_routing"]       = "Routage en oignon",
        ["danger_zone"]         = "ZONE DANGEREUSE",
        ["contacts"]            = "Contacts",
    };

    // ── GERMAN ────────────────────────────────────────────────────────
    private static readonly Dictionary<string, string> German = new()
    {
        ["app_name"]            = "hysj",
        ["cancel"]              = "Abbrechen",
        ["save"]                = "Speichern",
        ["delete"]              = "Löschen",
        ["confirm"]             = "Bestätigen",
        ["loading"]             = "Lädt...",
        ["error"]               = "Fehler",
        ["ok"]                  = "OK",
        ["back"]                = "Zurück",
        ["send"]                = "Senden",
        ["search"]              = "Suchen",
        ["settings"]            = "Einstellungen",
        ["language"]            = "Sprache",
        ["select_language"]     = "Sprache auswählen",
        ["login"]               = "Anmelden",
        ["register"]            = "Registrieren",
        ["username"]            = "Benutzername",
        ["password"]            = "Passwort",
        ["login_title"]         = "Willkommen zurück",
        ["login_subtitle"]      = "Melde dich an, um fortzufahren",
        ["register_title"]      = "Konto erstellen",
        ["totp_title"]          = "Zwei-Faktor-Authentifizierung",
        ["totp_code"]           = "6-stelligen Code eingeben",
        ["logout"]              = "Abmelden",
        ["conversations"]       = "Gespräche",
        ["welcome"]             = "Willkommen, {0}",
        ["new_conversation"]    = "Neues Gespräch",
        ["groups"]              = "Gruppen",
        ["encrypted"]           = "Verschlüsselt",
        ["type_message"]        = "Nachricht",
        ["anonymous_badge"]     = "Du bist anonym in dieser Gruppe als «{0}»",
        ["create_group"]        = "Gruppe erstellen",
        ["security"]            = "Sicherheit",
        ["danger_zone"]         = "GEFAHRENZONE",
        ["contacts"]            = "Kontakte",
    };

    // ── ARABIC ────────────────────────────────────────────────────────
    private static readonly Dictionary<string, string> Arabic = new()
    {
        ["app_name"]            = "hysj",
        ["cancel"]              = "إلغاء",
        ["save"]                = "حفظ",
        ["delete"]              = "حذف",
        ["confirm"]             = "تأكيد",
        ["loading"]             = "جار التحميل...",
        ["error"]               = "خطأ",
        ["ok"]                  = "موافق",
        ["back"]                = "رجوع",
        ["send"]                = "إرسال",
        ["search"]              = "بحث",
        ["settings"]            = "الإعدادات",
        ["language"]            = "اللغة",
        ["select_language"]     = "اختر اللغة",
        ["login"]               = "تسجيل الدخول",
        ["register"]            = "إنشاء حساب",
        ["username"]            = "اسم المستخدم",
        ["password"]            = "كلمة المرور",
        ["login_title"]         = "مرحباً بعودتك",
        ["login_subtitle"]      = "سجّل دخولك للمتابعة",
        ["register_title"]      = "إنشاء حساب جديد",
        ["totp_title"]          = "المصادقة الثنائية",
        ["totp_code"]           = "أدخل الرمز المكون من 6 أرقام",
        ["logout"]              = "تسجيل الخروج",
        ["conversations"]       = "المحادثات",
        ["welcome"]             = "مرحباً، {0}",
        ["groups"]              = "المجموعات",
        ["encrypted"]           = "مشفّر",
        ["type_message"]        = "رسالة",
        ["anonymous_badge"]     = "أنت مجهول في هذه المجموعة باسم «{0}»",
        ["security"]            = "الأمان",
        ["contacts"]            = "جهات الاتصال",
    };

    // ── CHINESE ───────────────────────────────────────────────────────
    private static readonly Dictionary<string, string> Chinese = new()
    {
        ["app_name"]            = "hysj",
        ["cancel"]              = "取消",
        ["save"]                = "保存",
        ["delete"]              = "删除",
        ["confirm"]             = "确认",
        ["loading"]             = "加载中...",
        ["error"]               = "错误",
        ["ok"]                  = "确定",
        ["back"]                = "返回",
        ["send"]                = "发送",
        ["search"]              = "搜索",
        ["settings"]            = "设置",
        ["language"]            = "语言",
        ["select_language"]     = "选择语言",
        ["login"]               = "登录",
        ["register"]            = "注册",
        ["username"]            = "用户名",
        ["password"]            = "密码",
        ["login_title"]         = "欢迎回来",
        ["login_subtitle"]      = "登录以继续",
        ["register_title"]      = "创建账号",
        ["totp_title"]          = "双重验证",
        ["totp_code"]           = "输入6位验证码",
        ["logout"]              = "退出登录",
        ["conversations"]       = "对话",
        ["welcome"]             = "欢迎，{0}",
        ["groups"]              = "群组",
        ["encrypted"]           = "已加密",
        ["type_message"]        = "消息",
        ["anonymous_badge"]     = "你在此群组中匿名显示为「{0}」",
        ["security"]            = "安全",
        ["contacts"]            = "联系人",
    };

    // ── PORTUGUESE ────────────────────────────────────────────────────
    private static readonly Dictionary<string, string> Portuguese = new()
    {
        ["app_name"]            = "hysj",
        ["cancel"]              = "Cancelar",
        ["save"]                = "Salvar",
        ["delete"]              = "Excluir",
        ["confirm"]             = "Confirmar",
        ["loading"]             = "Carregando...",
        ["error"]               = "Erro",
        ["ok"]                  = "OK",
        ["back"]                = "Voltar",
        ["send"]                = "Enviar",
        ["search"]              = "Pesquisar",
        ["settings"]            = "Configurações",
        ["language"]            = "Idioma",
        ["select_language"]     = "Selecionar idioma",
        ["login"]               = "Entrar",
        ["register"]            = "Cadastrar",
        ["username"]            = "Usuário",
        ["password"]            = "Senha",
        ["login_title"]         = "Bem-vindo de volta",
        ["login_subtitle"]      = "Entre para continuar",
        ["register_title"]      = "Criar conta",
        ["totp_title"]          = "Autenticação em dois fatores",
        ["totp_code"]           = "Digite o código de 6 dígitos",
        ["logout"]              = "Sair",
        ["conversations"]       = "Conversas",
        ["welcome"]             = "Bem-vindo, {0}",
        ["groups"]              = "Grupos",
        ["encrypted"]           = "Criptografado",
        ["type_message"]        = "Mensagem",
        ["anonymous_badge"]     = "Você é anônimo neste grupo como «{0}»",
        ["security"]            = "Segurança",
        ["contacts"]            = "Contatos",
    };

    // ── RUSSIAN ───────────────────────────────────────────────────────
    private static readonly Dictionary<string, string> Russian = new()
    {
        ["app_name"]            = "hysj",
        ["cancel"]              = "Отмена",
        ["save"]                = "Сохранить",
        ["delete"]              = "Удалить",
        ["confirm"]             = "Подтвердить",
        ["loading"]             = "Загрузка...",
        ["error"]               = "Ошибка",
        ["ok"]                  = "ОК",
        ["back"]                = "Назад",
        ["send"]                = "Отправить",
        ["search"]              = "Поиск",
        ["settings"]            = "Настройки",
        ["language"]            = "Язык",
        ["select_language"]     = "Выбрать язык",
        ["login"]               = "Войти",
        ["register"]            = "Регистрация",
        ["username"]            = "Имя пользователя",
        ["password"]            = "Пароль",
        ["login_title"]         = "С возвращением",
        ["login_subtitle"]      = "Войдите, чтобы продолжить",
        ["register_title"]      = "Создать аккаунт",
        ["totp_title"]          = "Двухфакторная аутентификация",
        ["totp_code"]           = "Введите 6-значный код",
        ["logout"]              = "Выйти",
        ["conversations"]       = "Переписки",
        ["welcome"]             = "Добро пожаловать, {0}",
        ["groups"]              = "Группы",
        ["encrypted"]           = "Зашифровано",
        ["type_message"]        = "Сообщение",
        ["anonymous_badge"]     = "Вы анонимны в этой группе как «{0}»",
        ["security"]            = "Безопасность",
        ["contacts"]            = "Контакты",
    };

    // ── JAPANESE ──────────────────────────────────────────────────────
    private static readonly Dictionary<string, string> Japanese = new()
    {
        ["app_name"]            = "hysj",
        ["cancel"]              = "キャンセル",
        ["save"]                = "保存",
        ["delete"]              = "削除",
        ["confirm"]             = "確認",
        ["loading"]             = "読み込み中...",
        ["error"]               = "エラー",
        ["ok"]                  = "OK",
        ["back"]                = "戻る",
        ["send"]                = "送信",
        ["search"]              = "検索",
        ["settings"]            = "設定",
        ["language"]            = "言語",
        ["select_language"]     = "言語を選択",
        ["login"]               = "ログイン",
        ["register"]            = "登録",
        ["username"]            = "ユーザー名",
        ["password"]            = "パスワード",
        ["login_title"]         = "おかえりなさい",
        ["login_subtitle"]      = "続けるにはログインしてください",
        ["register_title"]      = "アカウント作成",
        ["totp_title"]          = "二段階認証",
        ["totp_code"]           = "6桁のコードを入力",
        ["logout"]              = "ログアウト",
        ["conversations"]       = "会話",
        ["welcome"]             = "ようこそ、{0}",
        ["groups"]              = "グループ",
        ["encrypted"]           = "暗号化済み",
        ["type_message"]        = "メッセージ",
        ["anonymous_badge"]     = "このグループでは「{0}」として匿名です",
        ["security"]            = "セキュリティ",
        ["contacts"]            = "連絡先",
    };
}
